/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConferenteRouteImport } from './routes/conferente'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenteRoute = ConferenteRouteImport.update({
  id: '/conferente',
  path: '/conferente',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conferente': typeof ConferenteRoute
  '/convite': typeof ConviteRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conferente': typeof ConferenteRoute
  '/convite': typeof ConviteRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conferente': typeof ConferenteRoute
  '/convite': typeof ConviteRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/conferente' | '/convite' | '/redefinir-senha'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/conferente' | '/convite' | '/redefinir-senha'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/conferente'
    | '/convite'
    | '/redefinir-senha'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConferenteRoute: typeof ConferenteRoute
  ConviteRoute: typeof ConviteRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferente': {
      id: '/conferente'
      path: '/conferente'
      fullPath: '/conferente'
      preLoaderRoute: typeof ConferenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConferenteRoute: ConferenteRoute,
  ConviteRoute: ConviteRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
